movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<movie_id>', views.detail, name='detail'),
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource, GenreResource
from . import views

movie_resource = MovieResource()
genre_resource = GenreResource()

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls)),
    path('api/', include(genre_resource.urls)),
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie, Genre

# Create your models here.


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']


class GenreResource(ModelResource):
    class Meta:
        queryset = Genre.objects.all()
        resource_name = 'genres'

movies/models.py
from email.policy import default
from django.db import models
from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=200)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.


def index(request):
    # SELECT * FROM movies_movie
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):

    # SELECT * FROM movies_movie WHERE id = movie_id
    movie = get_object_or_404(Movie, id=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %} {% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{movie.title}}</dd>
  <dt>Genre</dt>
  <dd>{{movie.genre}}</dd>
  <dt>Stock</dt>
  <dd>{{movie.number_in_stock}}</dd>
</dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %} {% block content %}
<!-- Make a table of movie list -->

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Release Year</th>
      <th scope="col">Genre</th>
      <th scope="col">Daily Rate</th>
      <th scope="col">Number in Stock</th>
    </tr>
  </thead>
  <tbody>
    <!-- Loop through the movies list -->
    {% for movie in movies %}
    <tr>
      <td>
        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
      </td>
      <td>{{ movie.release_year }}</td>
      <td>{{ movie.genre }}</td>
      <td>{{ movie.daily_rate }}</td>
      <td>{{ movie.number_in_stock }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    {% comment %} Material Design Bootstrap Navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Vidly</a>
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link disabled"
                href="#"
                tabindex="-1"
                aria-disabled="true"
                >Disabled</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main class="container">
      <div class="my-5"></div>
      {% block content %} {% endblock %}
    </main>
    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"
    ></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% block content %}
<h2>
  <a href="{% url 'movies:index' %}">Movies</a>
</h2>
{% endblock %}